# Generated by Django 3.1 on 2020-08-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_table', models.CharField(max_length=99999)),
                ('pakistan_table', models.CharField(max_length=99999)),
                ('pak_stats', models.CharField(max_length=99999)),
                ('global_stats', models.CharField(max_length=99999)),
            ],
            options={
                'verbose_name_plural': 'Corona',
            },
        ),
    ]
